[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "b55eb1ceb241dcd9927f18818d9132ae87015176"
os = "macos"

    [[libosrmc.download]]
    sha256 = "2e7db923fac253ff2d5f719b8789c0dca1d1e573e733fd26621e71e2fd420afe"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "129fe08f0d0838bc41d9c3f2a43b7c47988424ab"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "d64a9652d4376159467bf177652859390bd928410b96f8b76a1bb8a7f0aef717"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "509c184829448299c8f4f3a8611612eb77a3e75c"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c9e8e2774a4a9d710782a9b90b4669e3a786e41a92cd5fc6f025aabbcf336f6d"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fac84e968f794424a8850a2ec7d50beeb15931f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "0e65921061239a563a490a2941c09e0bc62905d2cdcad8d18867bd140f4f3d10"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf8eea7e73b68549a40a89051179603a519ee18c"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "2c4ced665f709b1bd0b007db7ecb188e11a6e73978275b29e681a7eba238ba2c"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16bc16c4f1ce798a19cd6766aaa6aa4bd73f226a"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "6bdf0089034ba7fd654836eed373f891dd3e6865dfa46bc586babd1aca338377"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd4adc8d9578b00f4dee85ab398d4ac80e868711"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "d79c2183f34f54ece124d6727d198241ef114975df0d27462a0aad1159102d65"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cd1928833d50a73d387b336f62bc1d018dfc8d6"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b41f1ddae7886a8c9bae2da5b4ab5f08efe85c05c2746e1231d52561cfe3846c"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24d95922020ef1eb99836bf9f9a5bea9f842cd2b"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "da4c2ba290bd5a9d8591d005e9b0d8a3c2dad2e8d002a5ee481ab66edd4388fc"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c627471f03adbd60f3f78faaa61acee18f2472b"
os = "windows"

    [[libosrmc.download]]
    sha256 = "75a979bb748ebe67fa280f27d34fbdddd53dbfa91dcec47c4195442ab2d7454c"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5779046dd3769b51948fadc82daf3f5e21ae696c"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "00127a351af71dc0d418dd90a10e1c1e79120b22ed135edd6587b7b09a108f15"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e06bfc46090065afc00f00a17d85dcec94cc1d52"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "44993e1ffd161bb739712b10de48c434204515b362be4fd515def6552026c1a3"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "0752b5c099f6c83becf00841834a4f32417a25f9"
os = "macos"

    [[libosrmc.download]]
    sha256 = "8f234320e19f50dfb6eb40aedd04ee317a18b5cb96c3f242f5fca32acb233ce9"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.x86_64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f19bfd4ecadb98c186ffb629959732321f57934b"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "1e1a2d266e41ef0047ef31bbdc8f8f0a9b7bbe8e43cfe8e23ac86bd0038d250d"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a64fb4d612517a36469ca48d0301f465aa7be27"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f8fb11ee73fb2146012c218536f69ca9d357aab80908b106949fd62bb0f836a3"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a75f5d170b0d9e96fb691cc57624f9ae30048505"
os = "windows"

    [[libosrmc.download]]
    sha256 = "01d9efa7c88ace3727cb762c85e0d7dfe14df9aab60d3095376131f638c016dc"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v26.4.0+0/libosrmc.v26.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
