[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "cc9ed6f6c5321db0c815348ce78e3abe83df5596"
os = "macos"

    [[libosrmc.download]]
    sha256 = "a75357a47cac4756c5d1595239ac22d0f1e7552a4bafdbffefdb767e1ac35247"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e05f3d767be369f2b29269482ff32ef39016385"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "169dfb54b7798bdf0e2ef5bef8cf4222ad6afca6ae74e1681bf8e33b1a434f1a"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "252a43c67c6dcac678732b8394966aa689557575"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a1a5c84c214338c286feb5ace16320396732a19cb11a4296829135210070cb07"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb68e6fdb234d8814733932659be2d7a04ab3e45"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "aa27b703219abc6ba47aa5dfcc6aa41f1eed623f10262bbc19dacf9deb83aeba"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3df5f19e6c3d968d28524ac8e056b5a50077719c"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "e6260efd24756ba004315e8f39f46d49d03c01e4c328a34c9cfad90b5312944a"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75e8e4bcb45d4595b1c34e1dc29b7a2e2f34e387"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "1b6fd26291bf7d96b00ab668bf8e93df1fba8ad1208c09bec8cf5dded55eb637"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75a11dcdaf10d94d2a656b6f4a0c06c617c007e3"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "776bd896b88dbedf8eb459c49e3b62a53abee6d7fa2a6c693e627879a35d067f"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07f11c840a9b78c00515d719af6ff59f8b6b7a81"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "bd778d988488edcc4d551639d6179b24496ba97bc59b76087f555b7203dd3c3e"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c70c7a52f1d510169b6b015cc2c1600976334337"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "919eb9b8050f45930497c0aba3abddab3e45df9e22848d7f4db300f2f89cbc67"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3544f83f2c99a691030ffd7ad784a500205630e"
os = "windows"

    [[libosrmc.download]]
    sha256 = "43508bc73578e7e83ae743437c420041c5cceb8a450054b55bdf05b4b9b6effe"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "100769855b26de69744798fcdc4275f2060fa3ab"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "67f136248b1b35d23156a12e627041649a6846b06e0bfbad21c6c94ac5f1c00b"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e379ddc0a9b51be24d266f84d8e90021a8e3d81"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "8c489c877636cbca9ca8cd7bf7bc87040ca4d5a82cc034932db7b18a3b13e5bc"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3c7b261cb82bd992190d81e278303dfc6e86496"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "addc944fc0fbded3f0d4fa2d4b7cdec10ea659e1664edaa76f5f89e2806a242c"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "832e19c907422d5cab1d8643eec6359dc4cc10b8"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "6ca1457f8211c493c8af4b5066cd0ea85167095342150331b6095ebb4cc16741"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.x86_64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e50e718d50c7c2a249bfb42f83e2851c3c514bd6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "8a2597d0d98385d2e37c8f334d3621507ad1fd6c93b704d2d47fbb3b1ab3ac54"
    url = "https://github.com/JuliaBinaryWrappers/libosrmc_jll.jl/releases/download/libosrmc-v6.0.2+0/libosrmc.v6.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
